#!/bin/bash

if [[ $# != 2 ]]
then
	echo "Usage: $0 app.xml output.apk"
	echo "Or     $0 -install file.apk"
	exit 1
fi

apkdir=$(dirname $(readlink -f "$0"))
airtools="$apkdir/.."

xml="$1"
apk="$2"

if [[ "$OSTYPE" == 'cygwin' ]]
then
	adt="$apkdir/airsdk/adt.bat"
else
	adt="$apkdir/airsdk/adt"
fi

if [[ "$xml" != "-install" ]]
then
	cert="$apkdir/cert.pfx"
	
	if [[ "$OSTYPE" == 'cygwin' ]]
	then
		cert=$(cygpath -w "$cert")
	fi
	
	storepass=$(cat $apkdir/storepass.txt)
	files=$($airtools/appcontents.py "$xml")
	#files="game.swf 36x36-border.png 48x48-border.png 72x72-border.png"

	#airversion=$($adt -version)

	#cert=android-cert.pfx

	#target=apk
	target=apk-captive-runtime
	#target=apk-debug
	#target=apk-captive-runtime

	#AMAZON="-airDownloadURL http://www.amazon.com/gp/mas/dl/android?p=com.adobe.air"

	#DEBUG="-connect 192.168.0.16"
	#DEBUG=-listen
	
	#adb forward tcp:7936 tcp:7936
	#fdb -p 7936
	
	"$adt" -package -target $target $DEBUG $AMAZON -storetype pkcs12 -keystore "$cert" -storepass "$storepass" "$apk" "$xml" $files
	
	if [ $? -ne 0 ]
	then
		exit
	fi
fi

#"$adt" -installApp -platform android -package "$apk"

#"$adt" -launchApp -platform android -appid APP-ID-HERE

if [[ $(adb devices | wc -l) -gt 2 ]]
then
	echo Installing
	
	adb install -r "$apk"

	appid=$(aapt dump badging "$apk" | grep package | awk '{print $2}' | sed s/name=//g | sed s/\'//g)

	adb shell am start -n ${appid}/.AppEntry
else
	echo No devices connected
fi